name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm i
      - name: Build
        run: npm run build
      - name: Pack
        id: pack
        run: |
          filename=$(npm pack)
          echo "::set-output name=filename::`echo $filename`"
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            LICENSE
            ${{ steps.pack.outputs.filename }}
