name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Build
        run: |
          npm i
          npm run build
      - name: Publish
        id: publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          filename=$(npm publish --ignore-scripts)
          echo "::set-output name=filename::`echo $filename`"
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            LICENSE
            ${{ steps.publish.outputs.filename }}